sudo: false
language: node_js
node_js:
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"

env:
  - MARIA_VERSION=10.5
  - MARIA_VERSION=10.4
  - MARIA_VERSION=10.3
  - MARIA_VERSION=10.2
  - MARIA_VERSION=10.1
  - MARIA_VERSION=10
  - MARIA_VERSION=latest

services: docker

before_install:
  - docker run -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=test_database -d -p 3306:3306 mariadb:${MARIA_VERSION}

before_script:
  - npm run make:config

script:
  - npm run test:coverage

after_success:
  - npm run codecov
