os: linux
dist: focal
language: node_js
node_js:
  - "14"
  - "12"
  - "10"
  - "node"
  - "lts/*"

env:
  - MARIA_VERSION=10.5
  - MARIA_VERSION=latest

services: docker

before_install:
  - sudo /etc/init.d/mysql stop
  - docker run -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=test_database -d -p 3306:3306 mariadb:${MARIA_VERSION}

before_script:
  - npm run make:config
  - sleep 10 && npm run migration:run -- -c test -t test

script:
  - npm run test:coverage

after_success:
  - npm run codecov
