sudo: false
language: node
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

services: docker

before_install:
  - docker run -e MONGO_INITDB_ROOT_USERNAME=test -e MONGO_INITDB_ROOT_PASSWORD=test -d -p 27017:27017 mongo

script:
  - npm run test:coverage

after_success:
  - npm run coveralls
