sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - pip install tox tox-travis
  - pip install coverage coveralls

services: mongodb

before_script:
  - make wq8pw.ini

script:
  - tox

after_success:
  - coverage report
  - coveralls
