sudo: false
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"

env:
  - MONGO_VERSION=4.1
  - MONGO_VERSION=4.0
  - MONGO_VERSION=latest
  - MONGO_VERSION=unstable
  
services: docker

before_install:
  - docker run -e MONGO_INITDB_ROOT_USERNAME=test -e MONGO_INITDB_ROOT_PASSWORD=test -d -p 27017:27017 mongo:${MONGO_VERSION}

script:
  - npm run test:coverage

after_success:
  - npm run codecov
