sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install flask pycrypto pymongo
  - pip install tox tox-travis
  - pip install coverage coveralls

script:
  - tox

after_success:
  - coverage report
  - coveralls
