sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - pypy3.5-5.8.0

install:
  - pip install tox tox-travis
  - pip install coverage coveralls

services: mongodb

before_script:
  - mongo testdb --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - make before_test

script:
  - tox

after_success:
  - coverage report
  - coveralls
