version: '2'

services:
  app:
    build: "./"
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    links:
      - 'mongo'
    depends_on:
     - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - ./db:/date/db
