version: '2'

services:
  app:
    build: "./"
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    links:
      - 'maria'
    depends_on:
     - maria
  maria:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./db:/var/lib/mysql
